// Blog actions

// FETCH actions
export const BLOG_FETCH_REQUEST = 'BLOG_FETCH_REQUEST';
export const BLOG_FETCH_REQUEST_SUCCESS = 'BLOG_FETCH_REQUEST_SUCCESS';
export const BLOG_FETCH_REQUEST_FAILURE = 'BLOG_FETCH_REQUEST_FAILURE';

export const BLOG_FETCH_ALL_REQUEST = 'BLOG_FETCH_ALL_REQUEST';
export const BLOG_FETCH_ALL_REQUEST_SUCCESS = 'BLOG_FETCH_ALL_REQUEST_SUCCESS';
export const BLOG_FETCH_ALL_REQUEST_FAILURE = 'BLOG_FETCH_ALL_REQUEST_FAILURE';

// ADD actions
export const BLOG_ADD_REQUEST = 'BLOG_ADD_REQUEST';
export const BLOG_ADD_REQUEST_SUCCESS = 'BLOG_ADD_REQUEST_SUCCESS';
export const BLOG_ADD_REQUEST_FAILURE = 'BLOG_ADD_REQUEST_FAILURE';

// UPDATE actions
export const BLOG_UPDATE_REQUEST = 'BLOG_UPDATE_REQUEST';
export const BLOG_UPDATE_REQUEST_SUCCESS = 'BLOG_UPDATE_REQUEST_SUCCESS';
export const BLOG_UPDATE_REQUEST_FAILURE = 'BLOG_UPDATE_REQUEST_FAILURE';

// DELETE actions
export const BLOG_DELETE_REQUEST = 'BLOG_DELETE_REQUEST';
export const BLOG_DELETE_REQUEST_SUCCESS = 'BLOG_DELETE_REQUEST_SUCCESS';
export const BLOG_DELETE_REQUEST_FAILURE = 'BLOG_DELETE_REQUEST_FAILURE';

// CLEAN BLOG
export const CLEAN_BLOG_REQUEST = 'CLEAN_BLOG_REQUEST';

// SINGLE BLOG FETCH actions
export const SINGLE_BLOG_FETCH_REQUEST = 'SINGLE_BLOG_FETCH_REQUEST';
export const SINGLE_BLOG_FETCH_REQUEST_SUCCESS = 'SINGLE_BLOG_FETCH_REQUEST_SUCCESS';
export const SINGLE_BLOG_FETCH_REQUEST_FAILURE = 'SINGLE_BLOG_FETCH_REQUEST_FAILURE';

// CLEAN SINGLE BLOG
export const CLEAN_SINGLE_BLOG_REQUEST = 'CLEAN_SINGLE_BLOG_REQUEST';

// UPDATE USER
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_REQUEST_SUCCESS = 'USER_UPDATE_REQUEST_SUCCESS';
export const USER_UPDATE_REQUEST_FAILURE = 'USER_UPDATE_REQUEST_FAILURE';
